### ISSUE TITLE
When I use the YOLO_weight_extractor why the max-pool layer are not generated ?

### ISSUE THREAD

**Issue by zh0ngtian** [gliese581gg/YOLO_tensorflow#27]

**Comment by gliese581gg** [comment]
Hi! weight extractor extracts values of weights and biases. Max-Pool layers don't have any weights or biases so we don't need to generate pooling layers in weight extractor. When the YOLO.py builds the tensorflow network, it builds pooling layers correctly:)

**Comment by zh0ngtian** [comment]
Thanks a lot ! I ran the YOLO_builder.py successfully just now, but the generated files are .ckpt.data file and .ckpt.meta. Could you please tell me why two files generated and  which one can be used ? Thank you~
