### ISSUE TITLE
Hi, would you like to tell me why no softmax function used ?

### ISSUE THREAD

**Issue by zh0ngtian** [gliese581gg/YOLO_tensorflow#29]
Hi, would you like to tell me why no softmax function used ? And would you like to share your cfg file ?

**Comment by shamanez** [comment]
Read the paper. There is a different architecture for score function layer. It's like calculating a tensor. This code is for actually test run. Author has clearly mentioned it :)

**Comment by zh0ngtian** [comment]
Thank you for your answer !

**Comment by shamanez** [comment]
well it's like that. They needed to have a softmax function for class
classification it will be costly. I had that problem too :D :D. It's not so
clear. But if we find how they calculate P(Object) for each grid cell we
might come up with an answer. I think those probabilities clearly align
with IOU of bounding boxes.
