### ISSUE TITLE
Facing Problems While Testing

### ISSUE THREAD

**Issue by ghost** [gliese581gg/YOLO_tensorflow#4]
First, my sincere thanks for making the implementation available in tensorflow framework.

Problem 1: When I run on "small" weight file, I sometimes face the issue sometimes not even for the same image as present in the test folder.
The issue is "OverflowError: signed integer is less than minimum"

My PC specifics have a CPU RAM of 12gb and a GPU TITAN X

Problem 2: When I run on "tiny" weight file, the image after detection shows rectangle made on different parts even when testing multiple times on the same image. Also, the the custom setting seem not to work in my case.

Please do help. Thanks.

**Comment by sangramgupta** [comment]
python YOLO_small_tf.py argvs -fromfile /home/neo/Desktop/YOLO_tensorflow-master/test/person.jpg
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Building YOLO_small graph...
    Layer  1 : Type = Conv, Size = 7 * 7, Stride = 2, Filters = 64, Input channels = 3
    Layer  2 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  3 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 192, Input channels = 64
    Layer  4 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  5 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 128, Input channels = 192
    Layer  6 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 256, Input channels = 128
    Layer  7 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 256, Input channels = 256
    Layer  8 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  9 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  10 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 256, Input channels = 512
    Layer  11 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  12 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 256, Input channels = 512
    Layer  13 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  14 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 256, Input channels = 512
    Layer  15 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  16 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 256, Input channels = 512
    Layer  17 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  18 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 512, Input channels = 512
    Layer  19 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 512
    Layer  20 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  21 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 512, Input channels = 1024
    Layer  22 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 512
    Layer  23 : Type = Conv, Size = 1 * 1, Stride = 1, Filters = 512, Input channels = 1024
    Layer  24 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 512
    Layer  25 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 1024
    Layer  26 : Type = Conv, Size = 3 * 3, Stride = 2, Filters = 1024, Input channels = 1024
    Layer  27 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 1024
    Layer  28 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 1024
    Layer  29 : Type = Full, Hidden = 512, Input dimension = 50176, Flat = 1, Activation = 1
    Layer  30 : Type = Full, Hidden = 4096, Input dimension = 512, Flat = 0, Activation = 1
    Layer  32 : Type = Full, Hidden = 1470, Input dimension = 4096, Flat = 0, Activation = 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:06:00.0
Total memory: 12.00GiB
Free memory: 11.31GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
Loading complete!

neo@neo-PC:~/Desktop/YOLO_tensorflow-master$ python YOLO_tiny_tf.py -fromfile /home/neo/Desktop/YOLO_tensorflow-master/test/person.jpg
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Building YOLO_tiny graph...
    Layer  1 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 16, Input channels = 3
    Layer  2 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  3 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 32, Input channels = 16
    Layer  4 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  5 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 64, Input channels = 32
    Layer  6 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  7 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 128, Input channels = 64
    Layer  8 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  9 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 256, Input channels = 128
    Layer  10 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  11 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 512, Input channels = 256
    Layer  12 : Type = Pool, Size = 2 * 2, Stride = 2
    Layer  13 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 512
    Layer  14 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 1024
    Layer  15 : Type = Conv, Size = 3 * 3, Stride = 1, Filters = 1024, Input channels = 1024
    Layer  16 : Type = Full, Hidden = 256, Input dimension = 50176, Flat = 1, Activation = 1
    Layer  17 : Type = Full, Hidden = 4096, Input dimension = 256, Flat = 0, Activation = 1
    Layer  19 : Type = Full, Hidden = 1470, Input dimension = 4096, Flat = 0, Activation = 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:06:00.0
Total memory: 12.00GiB
Free memory: 11.29GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
Loading complete!

Detect from /home/neo/Desktop/YOLO_tensorflow-master/test/person.jpg
    class : aeroplane , [x,y,w,h]=[-48087,13793,46535392,13576426], Confidence = 402645.15625
    class : boat , [x,y,w,h]=[24310,-23439,51588304,688320], Confidence = 330246.90625
    class : bird , [x,y,w,h]=[-36345,5273,212696448,13854367], Confidence = 302334.96875
    class : aeroplane , [x,y,w,h]=[-23591,16670,84860912,8163086], Confidence = 290672.4375
    class : aeroplane , [x,y,w,h]=[-17023,-9766,120443280,122156112], Confidence = 276793.0625
    class : aeroplane , [x,y,w,h]=[-16792,-4123,50658,8933030], Confidence = 261131.125
    class : aeroplane , [x,y,w,h]=[12342,-13735,3928485,17789012], Confidence = 228904.6875
    class : bicycle , [x,y,w,h]=[-33579,5285,109907528,22440176], Confidence = 225240.109375
    class : bird , [x,y,w,h]=[-38960,-1755,7142519,1693077], Confidence = 215890.609375
    class : aeroplane , [x,y,w,h]=[-13753,16424,551394,1025716], Confidence = 200010.890625
    class : aeroplane , [x,y,w,h]=[8313,16703,124939400,3539051], Confidence = 199425.578125
    class : aeroplane , [x,y,w,h]=[-6310,-2630,99439032,48301752], Confidence = 198307.828125
    class : aeroplane , [x,y,w,h]=[-10927,15864,1157316,16085480], Confidence = 189916.875
    class : aeroplane , [x,y,w,h]=[-23781,-7608,25967836,1907584], Confidence = 168935.6875
    class : boat , [x,y,w,h]=[17930,-22094,17036760,25118172], Confidence = 162985.78125
    class : bird , [x,y,w,h]=[-49488,5417,62607808,35490064], Confidence = 160399.203125
    class : bicycle , [x,y,w,h]=[-14357,511,11368502,11860380], Confidence = 147718.0625
    class : bicycle , [x,y,w,h]=[-28864,-7339,2347652,4729], Confidence = 144536.421875
    class : bird , [x,y,w,h]=[7154,-1183,8640866,38136876], Confidence = 127100.921875
    class : bicycle , [x,y,w,h]=[14168,4647,24167038,4545683], Confidence = 117873.039062
    class : bicycle , [x,y,w,h]=[50358,-6118,7747459,523973], Confidence = 99729.2421875
    class : bird , [x,y,w,h]=[6203,-2775,34590704,305773], Confidence = 99652.6796875
    class : aeroplane , [x,y,w,h]=[20392,-11218,4870148,9638937], Confidence = 92635.9453125
    class : aeroplane , [x,y,w,h]=[-42954,8530,17287768,52852516], Confidence = 91994.125
    class : aeroplane , [x,y,w,h]=[-28935,473,666865,26972968], Confidence = 81152.5390625
    class : aeroplane , [x,y,w,h]=[38963,3170,3221926,1946462], Confidence = 64643.6523438
    class : aeroplane , [x,y,w,h]=[-5165,8273,411560,2943558], Confidence = 61782.2070312
    class : bicycle , [x,y,w,h]=[-186,7742,4134439,35237484], Confidence = 56591.6640625
    class : aeroplane , [x,y,w,h]=[-23053,26327,174865,696003], Confidence = 55206.9257812
    class : aeroplane , [x,y,w,h]=[-27147,8941,40154736,56718500], Confidence = 52441.4257812
    class : aeroplane , [x,y,w,h]=[39206,2040,540533952,47124872], Confidence = 39997.3085938
    class : bicycle , [x,y,w,h]=[-54098,5933,15475782,919548], Confidence = 39955.1601562
    class : boat , [x,y,w,h]=[-5884,-1115,436774,16083269], Confidence = 39585.7421875
    class : bicycle , [x,y,w,h]=[8033,1507,41099732,156722], Confidence = 38102.3203125
    class : bicycle , [x,y,w,h]=[16939,-1929,48290076,2115855], Confidence = 37710.6210938
    class : aeroplane , [x,y,w,h]=[-4181,-1479,98094,4891279], Confidence = 36842.0820312
    class : bicycle , [x,y,w,h]=[13910,-20216,2355916,79707248], Confidence = 33596.515625
    class : aeroplane , [x,y,w,h]=[-23941,3214,91907,2763142], Confidence = 32159.4609375
    class : bird , [x,y,w,h]=[5104,22972,1096115,54475920], Confidence = 31949.0722656
    class : aeroplane , [x,y,w,h]=[-17336,2752,3657764,121143], Confidence = 28670.6152344
    class : aeroplane , [x,y,w,h]=[-31265,8565,109507032,634294], Confidence = 26864.5546875
    class : aeroplane , [x,y,w,h]=[30933,-19427,16008010,4022], Confidence = 24132.3066406
    class : aeroplane , [x,y,w,h]=[-24425,-3857,2729713,4152849], Confidence = 24118.7890625
    class : bicycle , [x,y,w,h]=[-2847,11714,129234,147287], Confidence = 22377.1894531
    class : aeroplane , [x,y,w,h]=[-26303,15187,14614254,2852], Confidence = 17708.4199219
    class : bicycle , [x,y,w,h]=[-21499,14851,818535,74761], Confidence = 11080.6416016
    class : bicycle , [x,y,w,h]=[-47086,-8847,1630257,9516632], Confidence = 9180.43652344
    class : aeroplane , [x,y,w,h]=[23935,9810,1436925,3848821], Confidence = 7006.27490234
    class : aeroplane , [x,y,w,h]=[-29994,-1128,6404361,3114], Confidence = 6406.27441406
    class : aeroplane , [x,y,w,h]=[3625,-563,25381788,10845394], Confidence = 4624.40625
    class : aeroplane , [x,y,w,h]=[-28732,8400,68,2553425], Confidence = 4173.83154297
Elapsed time : 1.6171708107 secs
